### ISSUE TITLE
Funciones en Servicios Realizados 

### ISSUE THREAD

**Issue by clauf30** [Gabriel0617/backend-web-project#6]
1- Función que me devuelva todos los números de las hojas de ruta del backend.

2- Función que me devuelva todos los nombres de los Servicios PLANIFICADOS que existen en el backend.

3- Función que dado un id me devuelva el nombre del servicio PLANIFICADO.

4- Funcion que dado un id me devuelva el numero de la hoja de ruta.

5- Funcion que dado un nombre del servicio PLANIFICADO me devuelva el id. (el nombre del servicio planificado tiene que ser unico)

6- Funcion que dado un numero de la hoja de ruta me devuelva el id. (el numero de la hoja de ruta debe ser unico)

**Comment by Gabriel0617** [comment]
ya
